### ISSUE TITLE
SQL DATA BASE ERROR

### ISSUE THREAD

**Issue by sergio03spm** [HumanTree92/esx_extraitems#18]
![image](https://user-images.githubusercontent.com/67983987/86856843-7efbbb00-c0bd-11ea-8d6f-7e5e03697ebf.png)

This error pops up when uploadind the sql.

**Questions**
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
What Version of es_extended are you using?: latest
Are you using a Pre-Installed ESX?: yes
Are you using Essentialmode?: yes
Are you using OneSync?: idk
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Ur missing the weight column.  Don't lie on the questions or u will be banned.

**Comment by sergio03spm** [comment]
where did I lie?

**Comment by sergio03spm** [comment]
tell me how to add the weigh column please

**Comment by HumanTree92** [comment]
The es_extended V1 final has the weight column in the SQL. When u say latest it doesn't help with shit since the latest of es_extended is v2 which doesn't work with any esx_ resources. Also what pre-installed version of esx do u have. Sesx?
