### ISSUE TITLE
error shop 

### ISSUE THREAD

**Issue by tmgbdark** [HumanTree92/esx_extraitems#2]
Error running system event handling function for resource esx_shops: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:43: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:43: in function 'LoadShop'
        server/main.lua:10: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by HumanTree92** [comment]
Thats not this. But i had that same problem. Go to your DB then Items & make sure the Dark Net chip is set to darknet. But that error is esx_shops. And the problem comes down to the shop finding an item that isn't there.

**Comment by SanderAli** [comment]
The problem is with 2 items in the store.

-> blowpipe
-> fixkit

Fix error

Add 

INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES

	('blowpipe', 'blowpipe', 1, 0, 1),
	('fixkit', 'fixkit', 1, 0, 1);

PD: Thanks HumanTree92 for reducing the number of scripts.

**Comment by tmgbdark** [comment]
where is shop?

**Comment by HumanTree92** [comment]
@tmgbdark  You will need to add these items to a Shop.
