### ISSUE TITLE
weapon ammo bxo and weapon ammo clip not work...

### ISSUE THREAD

**Issue by YInfeRnal** [HumanTree92/esx_extraitems#22]
**Describe the Bug | A Clear & Concise Description of Bug**
weapon ammo bxo and weapon ammo clip not work...

**Questions**
Have you looked through the Closed Topics?: yea
Have you looked through the Wiki?: yea
What Version of es_extended are you using?: extendedmode
Are you using a Pre-Installed ESX?: no
Are you using Essentialmode?: yea
Are you using OneSync?: yea
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_extraitems/issues/17

**Comment by YInfeRnal** [comment]
this not working.. he say I think I did some shit, closing for now.
and close
i check and do that but not working
100% not work

**Comment by HumanTree92** [comment]
Do what??? This is a duplicate of another issue. I have 2 different fixes that i am currently testing.
