### ISSUE TITLE
Ammo Box and Clip for Different Weapon

### ISSUE THREAD

**Issue by awidyaandika** [HumanTree92/esx_extraitems#23]
Hello, I want to ask something again. before that thx to @HumanTree92 to answer my question about Clip Nil on esx_advancedweaponshop.

So, my question is how to make ammo box and clip for specific weapons or specific types?

**Comment by HumanTree92** [comment]
Well if your talking about making a Weapon Clip for Pistols & another Weapon Clip for AR's you would need to do something like https://github.com/HumanTree92/esx_extraitems/commit/bb967eba54a895913bbbc67f1ba65aef5213c519 but make Different Configs for each type of weapon & you would need to make different checks to make sure your using the right Clip for the right Type. Not sure if i explained it well or not. I can look into adding different Weapon Clips for the different Types of Weapons in the future. I would do something like removing Weapon Box & adding Multiple Weapon Clips for the different types of Guns like Pistol, AR, Shotgun, etc.

**Comment by awidyaandika** [comment]
> I can look into adding different Weapon Clips for the different Types of Weapons in the future. I would do something like removing Weapon Box & adding Multiple Weapon Clips for the different types of Guns like Pistol, AR, Shotgun, etc.

Oke, I can't wait for it 👍

**Comment by awidyaandika** [comment]
@HumanTree92 I want to ask something again. Why my weapon ammo, sometimes does not sync when I re-join the server?

Example:
I have 2 pistols in my inventory, the ammo is 430, then I disconnect from the server and then I join again to the server. My pistol ammo reduces 430 to 24.
And this also happens in shotgun weapons,

Assumption:
I think the problem in a similar weapon (same type), I try to buy 1000 ammo and only have 1 weapon and the ammo sync works but I buy 1000 ammo and have 2 weapons with the same type, the ammo will reset to 24 ammo after I re-join to the server.

Do you have solution about this problem?

**Comment by HumanTree92** [comment]
If ammo is not syncing it something to do with ESX not this script. That is a question i would ask on es_extended.

**Comment by awidyaandika** [comment]
Oke, thx @HumanTree92 for the answer 👍
