### ISSUE TITLE
Weaclip not giving ammo

### ISSUE THREAD

**Issue by Amparrr** [HumanTree92/esx_extraitems#24]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes i tried the solution did not work
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: zap hosting
Are you using es_extended? If Yes what Version? (Example: 1.2):  1
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows 
![image](https://user-images.githubusercontent.com/69942106/90699624-ac6e8380-e27b-11ea-8274-2af5f7cb1b44.png)

**Comment by HumanTree92** [comment]
Are you using Zaps pre-installed ESX?

**Comment by Amparrr** [comment]
yes sir

**Comment by HumanTree92** [comment]
I would suggest not using theirs. As theirs isn't updated to support my scripts. You must be using es_extended V1 Final or Extendedmode. Zaps ESX is way behind

**Comment by Amparrr** [comment]
can you drop a link for the esx_extended im supposed to use

**Comment by HumanTree92** [comment]
Check the Readme. It has both links

**Comment by Amparrr** [comment]
when i update it it messes up my database do i need to reinstall my database then install the new es_extended?

**Comment by HumanTree92** [comment]
U would need to reinstall everything from the ESX GitHub. This is why u don't use zap.

**Comment by Amparrr** [comment]
do you have a link to the esx github?

**Comment by HumanTree92** [comment]
[Here is ExtendedMode](https://github.com/extendedmode) & [Here is ESX Community](https://github.com/esx-community) & [Here is ESX Framework](https://github.com/esx-framework)
