### ISSUE TITLE
Bullet Proof 

### ISSUE THREAD

**Issue by Amparrr** [HumanTree92/esx_extraitems#25]
is there any way i could disable when you use the item 'bulletproof' you could disable where the vest shows on your body

**Comment by HumanTree92** [comment]
U should be able to comment out or remove ``` SetPedComponentVariation(playerPed, 9, 27, 9, 2) ```

**Comment by Amparrr** [comment]
where do i change this

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_extraitems/blob/master/client/main.lua#L201

**Comment by KaoticServers** [comment]
Is there a way to make the "bulletproof" removeable? to where you can put it on and off?
