### ISSUE TITLE
Ammo not filling

### ISSUE THREAD

**Issue by epicgameruk** [HumanTree92/esx_extraitems#26]
**Describe the Bug | A Clear & Concise Description of Bug**
The ammo is not filling with my weapons, i am using advanced

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: 
I took the parts of the script i needed and put them in a separate script because i did not want things that i did not want causing issues
Have you looked through the Closed Topics?: 
yes
Have you looked through the Wiki?: 
yes
Are you using a Pre-Installed ESX? If Yes who?: 
yes zap
Are you using es_extended? If Yes what Version? (Example: 1.2): 
1.0 i think
Are you using Essentialmode?: 
yes
Are you using OneSync?: 
yes

**Comment by HumanTree92** [comment]
The problem is this code is meant to work with ESX V1 Final &/or ExtendedMode. Since you are using a Zaps Pre-Install this is your problem. Zaps Pre-Install is way outdated.

**Comment by epicgameruk** [comment]
Okay so your saying I need to reinstall all the scripts that came with that pack with the newest versions for it to work, would it work with v2

**Comment by HumanTree92** [comment]
No esx_ resource will work with V2. V2 is going to be an All in One Script similar to vRP. What i am saying is you must go to each scripts github and install them from there manually. Zap is Trash & outdated. I have had many people come to me with the same problems as you. When they tell me they are using Zaps Pre-Installed ESX thats their problem. Zaps Pre-Installed is way outdated for my scripts. My Scripts only support ESX V1 Final or ExtendedMode. You would need to download either one & then install each script from either ones githubs. I have them linked in the Readme. If you decide to use ESX V1 Final download the scripts from https://github.com/esx-framework and if you decide to use ExtendedMode download the scripts from https://github.com/extendedmode

**Comment by epicgameruk** [comment]
I use both es extended and essential mode, the newest essential mode

**Comment by epicgameruk** [comment]
Wait so could this also be my issue with esx kashacters

**Comment by HumanTree92** [comment]
It could be. In ESX V1 Final essentialmode doesn't work. If you want to use essentialmode you will need to use ExtendedMode.

**Comment by epicgameruk** [comment]
Now I'm confused, I'm unsure now i though essential mode and esx were always supposed to work together as it's what deals with the money. So if I was to upgrade to v1 final what would I need or is there a list of all the needed scripts for the esx versions

**Comment by HumanTree92** [comment]
A while back ESX ditched ES due to their shit code & other various problems. So for example if you decide to use ESX V1 Final u wouldn't be able to use EssentialMode or es_ resources. But if you decide to use ExtendedMode you can still use essentialmode and older esx_ resources and es_ resources.

**Comment by epicgameruk** [comment]
Okay thank you I'll take a look into this, no wonder my server has issues 😂

**Comment by HumanTree92** [comment]
A lot of people complain about not wanting to update. But honestly the time that it takes to setup an ESX V1 Final Server or ExtendedMode is only a couple of days. Now tweaking everything its a couple of more days.

**Comment by epicgameruk** [comment]
I'm going to get straight on it tomorrow, would all esx_ scripts still work as I have custom ones or would I need the newest one and re edit what I changed

**Comment by HumanTree92** [comment]
U would most likely need the newest ones and Re-Edit them.

**Comment by epicgameruk** [comment]
Okay thank you so much for your help

**Comment by epicgameruk** [comment]
So i am messing with v1 final now and most things are working but my kashacters is acting strange, i used this one which is a new ui and i am trying the original as well and for some reason the original doesnt load at all and the new design one loads but when i select a character nothing happens it just loads me as if there was no multiple characters

**Comment by epicgameruk** [comment]
Hey pal would you know how I can get kashacters to work as for some reason it dont load at all for me now i think it requires essentialmode

**Comment by HumanTree92** [comment]
Then i would suggest using extendedmode

**Comment by epicgameruk** [comment]
It should be working idk what's wrong with it is there any other just as good character creators

**Comment by HumanTree92** [comment]
Yeah i'm not sure. I'm not a huge fan of multiple characters.

**Comment by epicgameruk** [comment]
Okay no problem and for some reason I can't use the ammo boxes it doesn't come up with the option
