### ISSUE TITLE
unable to load ammo in to a weapon

### ISSUE THREAD

**Issue by captainbritian** [HumanTree92/esx_extraitems#27]
**Describe the Bug | A Clear & Concise Description of Bug**
i have been messing around adding scripts as i have needed them going down my list i get to adding in ammo for weapons from extra items while giving my self the ammo to see if the item its self works it does not give any ammo to the pistol 

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: 
no
Have you looked through the Closed Topics?: 
yess
Have you looked through the Wiki?: 
yes
Are you using a Pre-Installed ESX? If Yes who?: 
no
Are you using es_extended? If Yes what Version? (Example: 1.2): 
yes 1.2
Are you using Essentialmode?: 
no
Are you using ExtendedMode?: 
no
Are you using OneSync?: 
yes
Linux or Windows?: 
windows

**Comment by HumanTree92** [comment]
Have u tried using Extended V1 Final Or EXM?

**Comment by Locopengu96** [comment]
I have the same issue, if i click "use" on the Pistol ammo, nothing happens.

**Comment by HumanTree92** [comment]
You need to make sure that when weapons are in player inventories that in the DB the weapon name is like "WEAPON_PISTOL" and not "weapon_pistol".

**Comment by rizal499** [comment]
same problem there are no items that can be used .
