### ISSUE TITLE
Extra Items giving "bad argument #1 to 'unpack' on server console

### ISSUE THREAD

**Issue by ianvalls90** [HumanTree92/esx_extraitems#28]
**Describe the Bug | A Clear & Concise Description of Bug**

Well, I just installed this extraitems, and performed all the edits to the sql as needed, I go ingame, buy some ammo boxes (using advanced ammo system) and try empty my pistol, just to test, then I drag a Pistol Ammo Box to 'USE' button, my gun still has 0 bullets on it, and Im getting this error on server console:
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:831: bad argument #1 to 'unpack' (table expected, got nil)

So, after this, I tested a few more times, with different ammo boxes and different guns according, and it pops up everytime I try to use an ammo box.

--Later Edit: After this, I tested Binoculars, Bullet Proof and Oxygen Mask, and etc, everything seems to throw the same error on server side...

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: 
-No, fresh install.
Have you looked through the Closed Topics?: 
-Yes, didn't see anything alike.
Have you looked through the Wiki?: 
-Yes, already added it like the wiki states.
Are you using a Pre-Installed ESX? If Yes who?: 
-No.
Are you using es_extended? If Yes what Version? (Example: 1.2): 
-Yes, 1.2 (aka v1 Final)
Are you using Essentialmode?: 
-No.
Are you using ExtendedMode?: 
-No
Are you using OneSync?: 
-Yes, Legacy.
Linux or Windows?: 
-Windows, build 3074.

**Comment by HumanTree92** [comment]
Has nothing to do with my script. Everything works perfectly fine using the default inventory system.
