### ISSUE TITLE
there are no Ammo items that can be used.

### ISSUE THREAD

**Issue by rizal499** [HumanTree92/esx_extraitems#30]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): no
Are you using Essentialmode?: no
Are you using ExtendedMode?: yes
Are you using OneSync?: no
Linux or Windows?: 
windows

**Comment by HumanTree92** [comment]
Did u upload the sql and add the items to the correct shop? Also did you follow the Readme on How to add Stuff to your Shops:

**Comment by rizal499** [comment]
yes I've added all the items in the shop, 

still can't be used

**Comment by HumanTree92** [comment]
When you click on the item what options do you have?

**Comment by rizal499** [comment]
I don't use the "click inventory" but "drag and use inventory", 

i have "use , give , and drop options"

**Comment by rizal499** [comment]
the item seems unusable

**Comment by HumanTree92** [comment]
Are u using the default inventory system?

**Comment by rizal499** [comment]
no , I use inventory on this https://github.com/xtrsyz/esx_inventoryhud

**Comment by HumanTree92** [comment]
It works perfectly fine if you use the Default Inventory system. My guess would be the problem is with that inventory system. Have you tried adding the items to Config.CloseUiItems

**Comment by rizal499** [comment]
ohh okay, Thank you for your attention, i'll try it

**Comment by HumanTree92** [comment]
Yeah try that and if it doesn't work let me know. I will be leaving for Thanksgiving for the rest of the week. And if it doesn't work when i get back i will attempt to fix it.
