### ISSUE TITLE
Ammo not reload weapons

### ISSUE THREAD

**Issue by HaZeSh0cK** [HumanTree92/esx_extraitems#31]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): Yes 1.1
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Windows

https://user-images.githubusercontent.com/76493680/102923488-1e581300-4490-11eb-925e-69bbf11d5cdc.mov

**YES** the Weapons have the correct name in the Database. 

All other items except the weapons work perfectly

**Comment by HumanTree92** [comment]
This isn't an issue with this script at all. Could be the fact your using essentialmode and not es_extended. Yes they are 2 different frameworks. Could be b/c your not using ESX V1 Final.
