### ISSUE TITLE
How to EUP the Armor for Male/Female

### ISSUE THREAD

**Issue by johnsoul777** [HumanTree92/esx_extraitems#32]
Hello friend I have a question, I would like to have different bulletproof vests for men and women, I use the EUP package and obviously the models do not match, I had to change the code to make it work like this,

`RegisterNetEvent('esx_extraitems:bulletproof')
AddEventHandler('esx_extraitems:bulletproof', function()
	local playerPed = GetPlayerPed(-1)

	SetPedComponentVariation(playerPed, 9, 27, 5)
	AddArmourToPed(playerPed, 100)
	SetPedArmour(playerPed, 100)
end)`

the question is the following, how can I make the script differentiate between a male ped and a female ped?

the only difference is that for women it is number 29 instead of 27

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: Yes
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): no
Are you using Essentialmode?: no
Are you using ExtendedMode?: yes
Are you using OneSync?: yes
Linux or Windows?: Windows

**Comment by johnsoul777** [comment]
this is a man

![image](https://user-images.githubusercontent.com/72218928/103905280-b5fb6980-50fe-11eb-8918-d4fa994aba2f.png)

this is a women

![image](https://user-images.githubusercontent.com/72218928/103905349-c7dd0c80-50fe-11eb-8a68-658c47db5434.png)

obviously I would like women to be like that

![image](https://user-images.githubusercontent.com/72218928/103905432-e4794480-50fe-11eb-9a70-2d4ce3f613fa.png)

**Comment by johnsoul777** [comment]
Sorry for wasting your time friend, I found a solution, it would be good to implement it as update, I share it here in case someone else happens the same, just change the code a little,

```
RegisterNetEvent ('esx_extraitems: bulletproof')
AddEventHandler ('esx_extraitems: bulletproof', function ()
local playerPed = GetPlayerPed (-1)
local playerPedM = PlayerPedId ('mp_m_freemode_01')
local playerPedF = PlayerPedId ('mp_f_freemode_01')

SetPedComponentVariation (playerPedM, 9, 27, 5)
SetPedComponentVariation (playerPedF, 9, 29, 5)
AddArmourToPed (playerPed, 100)
SetPedArmour (playerPed, 100)
end)
```

**Comment by johnsoul777** [comment]
I had thought that this could solve it, in fact now the woman receives her corresponding bulletproof, but in the man it does not work

```
RegisterNetEvent('esx_extraitems:bulletproof')
AddEventHandler('esx_extraitems:bulletproof', function()
	local playerPed = GetPlayerPed(-1)
	local playerPedM = PlayerPedId('mp_m_freemode_01')
	local playerPedF = PlayerPedId('mp_f_freemode_01')
	
	SetPedComponentVariation(playerPedM, 9, 27, 5)
	SetPedComponentVariation(playerPedF, 9, 29, 5)
	AddArmourToPed(playerPed, 100)
	SetPedArmour(playerPed, 100)
end)
```

I can't think of any solution, I'm stuck ...

**Comment by HumanTree92** [comment]
You can do something like 	
```lua
TriggerEvent('skinchanger:getSkin', function(skin)
	if skin.sex == 0 then
		SetPedComponentVariation(playerPed, 9, 27, 5)
	else
		SetPedComponentVariation(playerPed, 9, 29, 5)
	end
end)
```

**Comment by johnsoul777** [comment]
> Puedes hacer algo como
> 
> ```lua
> TriggerEvent ( ' skinchanger: getSkin ' , function ( skin )
> 	 if skin. Sex  ==  0  then 
> 		SetPedComponentVariation ( playerPed , 9 , 27 , 5 )
> 	 else 
> 		SetPedComponentVariation ( playerPed , 9 , 29 , 5 )
> 	 end 
> end )
> ```

forgive me, I'm trying to learn LUA, but my English is very bad, would this be correct?

```
RegisterNetEvent('esx_extraitems:bulletproof')
AddEventHandler('esx_extraitems:bulletproof', function(skin)
	local playerPed = GetPlayerPed(-1)

	if skin.sex == 0 then 
		SetPedComponentVariation ( playerPed , 9 , 27 , 5 )
	else 
		SetPedComponentVariation ( playerPed , 9 , 29 , 5 )
	end 

	AddArmourToPed(playerPed, 100)
	SetPedArmour(playerPed, 100)
end)
```

because it's not working for me ...

**Comment by HumanTree92** [comment]
You have to have TriggerEvent('skinchanger:getSkin', function(skin) with the end)

**Comment by johnsoul777** [comment]
> Tienes que tener TriggerEvent ('skinchanger: getSkin', function (skin) con el final)

I am an idiot, now I have seen my failure, a thousand million thanks, now it works perfect, I leave a copy of the code in case someone else has the same problem

```
RegisterNetEvent('esx_extraitems:bulletproof')
AddEventHandler('esx_extraitems:bulletproof', function()
	local playerPed = GetPlayerPed(-1)

	TriggerEvent('skinchanger:getSkin', function(skin)
		if skin.sex == 0 then  
		  SetPedComponentVariation (playerPed, 9, 27, 5)
		else  
		  SetPedComponentVariation (playerPed, 9, 29, 5)
		end  
	end)

	AddArmourToPed(playerPed, 100)
	SetPedArmour(playerPed, 100)
end)
```

Have a happy new year friend!
