### ISSUE TITLE
Storage Bug

### ISSUE THREAD

**Issue by StreakFilms** [HumanTree92/esx_extraitems#33]
**Describe the Bug | A Clear & Concise Description of Bug**
When I try to put an item into storage it puts it and it says 1x NULL has been put into Storage
(Breaks the whole server) when I try to take it out of the storage I can't I get this error :

https://gyazo.com/975d71fc3e8f73d0c25ee79491860fcc

https://gyazo.com/1e5532239dd733b5d018c8b7494a66a6

Line : 851 https://prnt.sc/xxfiz9

It happens with Police job taxi job medic job and some gangs.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1 final
Are you using Essentialmode?: 
Are you using ExtendedMode?: +
Are you using OneSync?: Yes
Linux or Windows?:  Windows

**Comment by HumanTree92** [comment]
Did u upload the sql correctly? Also the videos ain't much help. Not in English so i don't know what ur doing.

**Comment by StreakFilms** [comment]
> Did u upload the sql correctly? Also the videos ain't much help. Not in English so i don't know what ur doing.

I do think so.I uploaded the SQL correctly.

And I'm trying to put objects into storage

**Comment by StreakFilms** [comment]
> Did u upload the sql correctly? Also the videos ain't much help. Not in English so i don't know what ur doing.

I do think so.I uploaded the SQL correctly.

And I'm trying to put objects into storage

**Comment by HumanTree92** [comment]
Can you send me what you put as the names. Maybe the Name is too long or has invalid characters. I honestly don't know

**Comment by StreakFilms** [comment]
> Can you send me what you put as the names. Maybe the Name is too long or has invalid characters. I honestly don't know

https://prnt.sc/yasnrp
https://prnt.sc/yaspdu

it's only for esx_extraitems like I can put guns normally and like bread and water but when I attach like a suppressor to a gun it same breaks the storage :/ I really need support on this one it's the biggest bug on my server as of right now

**Comment by HumanTree92** [comment]
Which items are causing problems. B/c fixkit & suppressor ain't even from this script.

**Comment by StreakFilms** [comment]
> Which items are causing problems. B/c fixkit & suppressor ain't even from this script.

It happens too with Bulletproof vest but the ammo boxes are working correctly

**Comment by HumanTree92** [comment]
I honestly don't have a clue. It could be something wrong in the database or something wrong like having 2 scripts collide with each other. But if it something to do with storing then its most likely a database error. If an item isn't working most some of the other stuff in the script is working then you might have another scripting colliding with it.

**Comment by StreakFilms** [comment]
> I honestly don't have a clue. It could be something wrong in the database or something wrong like having 2 scripts collide with each other. But if it something to do with storing then its most likely a database error. If an item isn't working most some of the other stuff in the script is working then you might have another scripting colliding with it.

So i fixed it it was with your esx extra items I downloaded mirrox extra items and it worked  :/

**Comment by HumanTree92** [comment]
Do you have a link so i can see whats different?

**Comment by HumanTree92** [comment]
Nvm i found it. Have fun using outdated code. Sorry i couldn't help. I have this installed on my server and many others use mine with 0 problems.
