### ISSUE TITLE
Handcuff in SQL not present in Main.lua server/client

### ISSUE THREAD

**Issue by tr1age** [HumanTree92/esx_extraitems#34]
**Describe the Bug | A Clear & Concise Description of Bug**
Handcuff and handcuff key are in the SQL but not in the main luas
Bug or just some left over sql items?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes

**Comment by HumanTree92** [comment]
They are meant to be added to your police script. It something i use in my server. In order to cuff someone you must have handcuffs and in order to uncuff someone you must have handcuff keys. They could also be used for a thief script. I was going to release mine but i'm not going to.

**Comment by therealnoskill** [comment]
why the handcuffs are not working on new legacy version?

**Comment by therealnoskill** [comment]
it was an awesome script and now i cant use handcuffs ;(
