### ISSUE TITLE
Weapon Box problem with GetweaponFromHash

### ISSUE THREAD

**Issue by DoesntMakeSense** [HumanTree92/esx_extraitems#35]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.1
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: Windows

Everything working but not the ammo boxes, This is the error im getting in txadmin live console
https://cdn.discordapp.com/attachments/743508421193760819/823147338234724392/unknown.png

**Comment by HumanTree92** [comment]
Try using ESX V1 Final not 1.1 as 1.1 hasn't been updated in over 2yrs.
