### ISSUE TITLE
Binoculars not working

### ISSUE THREAD

**Issue by twigmasters** [HumanTree92/esx_extraitems#36]
**Describe the Bug | A Clear & Concise Description of Bug**
I am trying to use the binoculars and when I try to use them nothing happens. I am using an inventory hud and I was able to buy them and see them in my inventory. I drag them over to use them and the inventory closes but nothing happens. I added binoculars to the "close menu" in the configuration of the inventory hud like I saw in another bug related to ammo.

Any suggestions?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1
Are you using Essentialmode?: yes version 
Are you using ExtendedMode?: 6.2.2
Are you using OneSync?: no
Linux or Windows?: windows

**Comment by twigmasters** [comment]
I found another binocular script that works.

**Comment by HumanTree92** [comment]
Maybe if u followed the readme it would have worked
