### ISSUE TITLE
bug defib

### ISSUE THREAD

**Issue by m0iises19** [HumanTree92/esx_extraitems#37]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: 
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: 
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using es_extended? If Yes what Version? (Example: 1.2): extended v1-final
Are you using Essentialmode?: 
Are you using ExtendedMode?: 
Are you using OneSync?: 
Linux or Windows?: windows

---------------------------------

the item "defib" does not revive people if you are not a doctor

**Comment by HumanTree92** [comment]
That isn't this scripts fault. Change it in esx_ambulancjob

**Comment by m0iises19** [comment]
@HumanTree92

still not working even changing "esx_ambulancjob"

**Comment by HumanTree92** [comment]
For example you need to remove this line https://github.com/esx-framework/esx_ambulancejob/blob/master/server/main.lua#L14 & https://github.com/esx-framework/esx_ambulancejob/blob/master/server/main.lua#L33

**Comment by m0iises19** [comment]
@HumanTree92 

I've deleted that and it still doesn't work

the defibrillator only works with doctors

**Comment by HumanTree92** [comment]
If its only working with doctors then it isn't this scripts fault. B/c Technically if you remove that line & do F8 refresh & then do restart esx_ambulancejob & then try to revive a dead player it should work. If not then you have something else blocking it in esx_ambulancejob. 

You can try setting line 14 of the server/main.lua to if xPlayer then
