### ISSUE TITLE
Please help/adding items to main shop not working

### ISSUE THREAD

**Issue by BubbaMisch** [HumanTree92/esx_extraitems#38]
**Describe the Bug | A Clear & Concise Description of Bug**
i need to add ammo to my esx_shops and i saw that this was one of the ways/only way. i run my 
es_extended.sql/esx_shop.sql/esx_extraitems_advammo.sql. after running all that i get a new db called (extended) with all those sql tables in it. problem is that the tables dont get added to my main db (paxsurvival) if that makes sense. ill add a picture so you can see. I know how to edit/add items in phpmyadmin and HeidiSQL. Im thinking my problem is that the items table from extraitems isnt being added to my (paxsurvival) db. There is an items table im my (paxsurvival) db but not the items i want. Ive tried editing my shops with items from both tables but nothing works unless its the table in (paxsurvival) and editing the shop table in (extended) with items from the items table in (extended) and that doesnt do anything. please help me with this im going crazy. I can add someone on discord if need for easier communication if needed. 

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: have not currently in new server
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: yes, cus idk what im doing and everything else im using works fine
Are you using es_extended? If Yes what Version? (Example: 1.2): yes
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: windows

![58d3cb863f866b93b7e628353c024e2a](https://user-images.githubusercontent.com/85641324/121407150-033d6a80-c92d-11eb-861e-fbd62f81c3e4.png)

**Comment by HumanTree92** [comment]
Change your database location here https://github.com/HumanTree92/esx_extraitems/blob/master/sqls/esx_extraitems_advammo.sql#L1

**Comment by BubbaMisch** [comment]
oh how do i do that? i havent looked yet for that but to make this a bit easier for me please :)

**Comment by BubbaMisch** [comment]
if you could do me a huge favor and talk like i know nothing lol i dont want to be a pain in the but but i can really use the help if you could explain how i change the db location.

**Comment by HumanTree92** [comment]
Go to this line https://github.com/HumanTree92/esx_extraitems/blob/master/sqls/esx_extraitems_advammo.sql#L1 & change es_extended to your Database name.
