### ISSUE TITLE
Attempt to call a nil value (field 'GetWeaponFromHash')

### ISSUE THREAD

**Issue by zakiyys** [HumanTree92/esx_extraitems#40]
**Describe the Bug | A Clear & Concise Description of Bug**
I get this error when trying to use the ammo to reload a gun.
![image](https://user-images.githubusercontent.com/77758375/128974465-59d3ff8a-5d75-4674-a0a7-4d3e6d07f381.png)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?:  Yes
Are you using a Pre-Installed ESX? If Yes who?: Yes, Ribsosay (ESX 3.5)
Are you using es_extended? If Yes what Version? (Example: 1.2): Yes, Not sure maybe v.2?
Are you using Essentialmode?: Not sure, maybe Yes (bcs there is this folder inside the resource)
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: Windows

Thank in advance

**Comment by HumanTree92** [comment]
Well if your using ESX V2 then no esx_ resources will work. I'm not sure what Version Ribsosay uses in ESX3.5. Your ESX will be something like 1.2, Legacy, or V2. Currently this script is being re-written for ESX Legacy.

**Comment by zakiyys** [comment]
okey then, can't wait for the new version. Thank you very much!

**Comment by iMajorLeague32-1** [comment]
HumanTree92, where you are rewritting the script for legacy would that (A) Apply to all of your scripts, and (B) should I go ahead and switch to Legacy from v1 Final

**Comment by HumanTree92** [comment]
> HumanTree92, where you are rewritting the script for legacy would that (A) Apply to all of your scripts, and (B) should I go ahead and switch to Legacy from v1 Final

I don't have the rewrite everything but for the most part i am working on updating all my scripts to work with Legacy. I would use Legacy as that is what most scripts are being switched to.
