### ISSUE TITLE
Weapon Kit

### ISSUE THREAD

**Issue by johndoe010** [HumanTree92/esx_extraitems#41]
**Describe the Bug | A Clear & Concise Description of Bug**
When using Weapon Kit, the UI won't open . It only allow me to browse the UI and not exactly getting in.
![Capture111111](https://user-images.githubusercontent.com/90406044/132719309-2516b1fb-3928-4125-8763-f91fe706d958.PNG)

**Questions**
Have you made changes to anything besides the `config.lua`?: Only in client.lua, changed functions which might collide with other functions such as aid kit and bandage
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using ESX Legacy?: No and 1.2, I used your previous version. 
Are you using OneSync?: Yes
Linux or Windows?: Yes

**Comment by HumanTree92** [comment]
I am currently in the process of switching all my scripts over to ESX Legacy. Yes there are some bugs but ESX Legacy will be a requirement.
