### ISSUE TITLE
Missing sql Save user database on sql bulletproof.

### ISSUE THREAD

**Issue by ghost** [HumanTree92/esx_extraitems#45]
CREATE TABLE `player_vests` (
  `identifier` varchar(255) NOT NULL,
  `armour` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `player_vests`
  ADD PRIMARY KEY (`identifier`);

**Comment by HumanTree92** [comment]
Nope. Has nothing to do with this script.
