### ISSUE TITLE
make a shop for items

### ISSUE THREAD

**Issue by saeedmasoudie** [HumanTree92/esx_extraitems#9]
hi for buy this item we need a shop i use esx_shops but i don't want to make a same blip with other shop like black shop with different blip and people know that this shop is different can you Introduction to me a black shop or help me for this problem
thanks

**Comment by HumanTree92** [comment]
Its not that hard to create an extra shop for esx_shops. Just copy a pre-existing shop and paste it. Then get the coords then add the name to the db.
